In [426]:
# Load libraries allow us to manipulate our data and navigate through the folders.
import pandas as pd
import numpy as np
import os
import csv

In [427]:
# Navigate to your working directory - the one that contains files with your input files: 
# input_data.csv and search_console_data.csv
os.chdir('YOUR-PATH')

In [428]:
# Part I.
# Pre-processing

In [429]:
# Get all search queries from your csv file and split into separate words.
output_df = pd.DataFrame(columns=['keyword', 'clicks'])
with open('input_data.csv') as f:
    rows = csv.reader(f)
    for row in rows:
        keyword_column = row[0]
        clicks_column = int(row[1])
        cost_column = float(row[2])
        transactions_column = int(row[3])
        keywords = keyword_column.split()
        for word in keywords:
            output_df = output_df.append({'keyword': word, 'clicks': clicks_column,'cost': cost_column, 'transactions': transactions_column}, ignore_index=True)
output_df

         keyword clicks    cost  transactions
0        actress      5   14.66           0.0
1      insurance      5   14.66           0.0
2           ship      8   30.94           0.0
3          cargo      8   30.94           0.0
4      insurance      8   30.94           0.0
5      architect      1    4.99           0.0
6             pl      1    4.99           0.0
7      insurance      1    4.99           0.0
8        builder      1    4.31           0.0
9         public      1    4.31           0.0
10     liability      1    4.31           0.0
11     insurance      1    4.31           0.0
12       channel     83  191.80           0.0
13       islands     83  191.80           0.0
14     insurance     83  191.80           0.0
15       brokers     83  191.80           0.0
16       compare      3   18.77           0.0
17        public      3   18.77           0.0
18     liability      3   18.77           0.0
19     insurance      3   18.77           0.0
20      computer      1    1.48           0.0
21    programmer      1    1.48           0.0
22     insurance      1    1.48           0.0
23    copywriter      6   23.08           0.0
24     insurance      6   23.08           0.0
25          cost      3   17.38           0.0
26            of      3   17.38           0.0
27        public      3   17.38           0.0
28     liability      3   17.38           0.0
29     insurance      3   17.38           0.0
...          ...    ...     ...           ...
1548   companies      1    5.39           0.0
1549      public      1    7.19           0.0
1550   liability      1    7.19           0.0
1551   insurance      1    7.19           0.0
1552         for      1    7.19           0.0
1553        sign      1    7.19           0.0
1554    erectors      1    7.19           0.0
1555      public      2   23.51           0.0
1556   liability      2   23.51           0.0
1557   insurance      2   23.51           0.0
1558         for      2   23.51           0.0
1559        sole      2   23.51           0.0
1560     traders      2   23.51           0.0
1561      public      1   11.82           0.0
1562   liability      1   11.82           0.0
1563   insurance      1   11.82           0.0
1564     limited      1   11.82           0.0
1565     company      1   11.82           0.0
1566        self      2    9.18           0.0
1567    employed      2    9.18           0.0
1568    domestic      2    9.18           0.0
1569     cleaner      2    9.18           0.0
1570   insurance      2    9.18           0.0
1571        self      7   59.24           0.0
1572    employed      7   59.24           0.0
1573      public      7   59.24           0.0
1574   liability      7   59.24           0.0
1575    surveyor      1    8.44           0.0
1576   liability      1    8.44           0.0
1577   insurance      1    8.44           0.0

[1578 rows x 4 columns]

In [430]:
# Check the data types in the above data frame.
# Clicks were converted to "object" when the words were splitted, and this is why we need to convert them into integers
# Also, transactions are floats and need to be converted into integers as well.
output_df.dtypes

keyword          object
clicks           object
cost            float64
transactions    float64
dtype: object

In [431]:
# Turn clicks into integers, tidy up transactions, make all words to lowercase.
output_df.clicks = output_df.clicks.astype('int64', copy=False)
output_df.transactions = output_df.transactions.astype('int64', copy=False)
output_df.keyword = output_df.keyword.str.lower()
output_df

         keyword  clicks    cost  transactions
0        actress       5   14.66             0
1      insurance       5   14.66             0
2           ship       8   30.94             0
3          cargo       8   30.94             0
4      insurance       8   30.94             0
5      architect       1    4.99             0
6             pl       1    4.99             0
7      insurance       1    4.99             0
8        builder       1    4.31             0
9         public       1    4.31             0
10     liability       1    4.31             0
11     insurance       1    4.31             0
12       channel      83  191.80             0
13       islands      83  191.80             0
14     insurance      83  191.80             0
15       brokers      83  191.80             0
16       compare       3   18.77             0
17        public       3   18.77             0
18     liability       3   18.77             0
19     insurance       3   18.77             0
20      computer       1    1.48             0
21    programmer       1    1.48             0
22     insurance       1    1.48             0
23    copywriter       6   23.08             0
24     insurance       6   23.08             0
25          cost       3   17.38             0
26            of       3   17.38             0
27        public       3   17.38             0
28     liability       3   17.38             0
29     insurance       3   17.38             0
...          ...     ...     ...           ...
1548   companies       1    5.39             0
1549      public       1    7.19             0
1550   liability       1    7.19             0
1551   insurance       1    7.19             0
1552         for       1    7.19             0
1553        sign       1    7.19             0
1554    erectors       1    7.19             0
1555      public       2   23.51             0
1556   liability       2   23.51             0
1557   insurance       2   23.51             0
1558         for       2   23.51             0
1559        sole       2   23.51             0
1560     traders       2   23.51             0
1561      public       1   11.82             0
1562   liability       1   11.82             0
1563   insurance       1   11.82             0
1564     limited       1   11.82             0
1565     company       1   11.82             0
1566        self       2    9.18             0
1567    employed       2    9.18             0
1568    domestic       2    9.18             0
1569     cleaner       2    9.18             0
1570   insurance       2    9.18             0
1571        self       7   59.24             0
1572    employed       7   59.24             0
1573      public       7   59.24             0
1574   liability       7   59.24             0
1575    surveyor       1    8.44             0
1576   liability       1    8.44             0
1577   insurance       1    8.44             0

[1578 rows x 4 columns]

In [432]:
# Sum up clicks, convs, costs.
final_df = output_df.groupby("keyword").sum()
final_df.reset_index(inplace=True)
final_df

          keyword  clicks     cost  transactions
0               &       1     5.36             0
1              10      99   534.08             2
2             10m       5    38.54             0
3               2      35   182.56             1
4               5      29   182.66             1
5              5m      23   185.38             0
6               a      39    81.46             0
7           actor      21    82.62             0
8          actors      27    44.28             0
9         actress       5    14.66             0
10          agent      15    74.37             0
11            air      67   191.72             7
12            and      11    58.15             1
13      architect      21   180.19             0
14           arts     930  4465.51             0
15         author      20    63.32             0
16           band      48   208.97             0
17          bands      79   282.11             0
18         barber      10    28.76             0
19      barrister      15    37.32             0
20         broker      20    89.21             0
21        brokers     137   464.12             4
22        builder       1     4.31             0
23       builders      15    93.69             0
24       building       1     5.05             0
25       business       1    17.67             0
26            buy       1     2.65             0
27           cake      45   245.90             0
28            car    1151  2516.71            28
29          cargo     904  3659.17            92
..            ...     ...      ...           ...
174          sole      86   639.42             2
175        sports      29    97.70             0
176         stall     321  1069.27             0
177   stallholder      11    27.63             0
178  stallholders      69   245.86             0
179        stalls     119   458.90             0
180    stonemason       1     0.19             0
181       student       4    20.49             0
182      students      22   123.06             0
183      surveyor      22    96.57             0
184     surveyors      16    79.86             0
185       teacher      13    42.58             0
186      teachers      38   107.65             0
187           the      15    24.74             0
188     therapist     181   541.66             0
189            to      29    82.76             0
190        trader     232  1255.33             0
191       traders     345  1990.96             2
192     tradesman       5    32.16             0
193       trading       2    11.93             0
194       transit      37   182.64            10
195     transport       2     8.70             0
196            uk     631  1921.64            44
197         union       1     8.17             0
198       vehicle     156   362.20             6
199      vehicles       1     3.41             1
200           web       1     3.40             0
201       website       2     5.94             0
202        window      15    57.31             0
203        worker       8    32.88             0

[204 rows x 4 columns]

In [433]:
# Save transactions with 0 conversions in a separate csv file.
final_output_result_no_convs = final_df[final_df.transactions == 0]
final_output_result_no_convs

          keyword  clicks     cost  transactions
0               &       1     5.36             0
2             10m       5    38.54             0
5              5m      23   185.38             0
6               a      39    81.46             0
7           actor      21    82.62             0
8          actors      27    44.28             0
9         actress       5    14.66             0
10          agent      15    74.37             0
13      architect      21   180.19             0
14           arts     930  4465.51             0
15         author      20    63.32             0
16           band      48   208.97             0
17          bands      79   282.11             0
18         barber      10    28.76             0
19      barrister      15    37.32             0
20         broker      20    89.21             0
22        builder       1     4.31             0
23       builders      15    93.69             0
24       building       1     5.05             0
25       business       1    17.67             0
26            buy       1     2.65             0
27           cake      45   245.90             0
30      carpenter       1     3.04             0
31     carpenters       1     7.74             0
32         carpet       3    17.19             0
33        channel     258   590.01             0
35       cheapest     123   861.40             0
36     children's      17    29.37             0
37      childrens     100   253.05             0
38          class      27    59.64             0
..            ...     ...      ...           ...
158     providers       2     9.18             0
160     publisher      36    85.08             0
161      quantity       2     7.99             0
166        school      16    67.41             0
171     shipments       2     3.70             0
173          sign       3     8.31             0
175        sports      29    97.70             0
176         stall     321  1069.27             0
177   stallholder      11    27.63             0
178  stallholders      69   245.86             0
179        stalls     119   458.90             0
180    stonemason       1     0.19             0
181       student       4    20.49             0
182      students      22   123.06             0
183      surveyor      22    96.57             0
184     surveyors      16    79.86             0
185       teacher      13    42.58             0
186      teachers      38   107.65             0
187           the      15    24.74             0
188     therapist     181   541.66             0
189            to      29    82.76             0
190        trader     232  1255.33             0
192     tradesman       5    32.16             0
193       trading       2    11.93             0
195     transport       2     8.70             0
197         union       1     8.17             0
200           web       1     3.40             0
201       website       2     5.94             0
202        window      15    57.31             0
203        worker       8    32.88             0

[153 rows x 4 columns]

In [434]:
# Write the result to csv.
final_output_result_no_convs.to_csv('1-lookup_words_no_convs.csv', index = False)

In [435]:
# Part II.
# Find words and word combinations from the Search Queries report that did not convert
# (now saved in 1-lookup_words_no_convs csv file) in your input_data.csv file.

In [436]:
# Read the file with words that did not convert, and save them into a list.
with open('1-lookup_words_no_convs.csv', 'r') as file:
  reader = csv.reader(file)
  lookup_words_no_convs = list(reader)
lookup_words_no_convs
lookup_words_no_convs_words = [item[0] for item in lookup_words_no_convs]
lookup_words_no_convs_words

['keyword',
 '&',
 '10m',
 '5m',
 'a',
 'actor',
 'actors',
 'actress',
 'agent',
 'architect',
 'arts',
 'author',
 'band',
 'bands',
 'barber',
 'barrister',
 'broker',
 'builder',
 'builders',
 'building',
 'business',
 'buy',
 'cake',
 'carpenter',
 'carpenters',
 'carpet',
 'channel',
 'cheapest',
 "children's",
 'childrens',
 'class',
 'cleaner',
 'cleaners',
 'cleaning',
 'club',
 'coach',
 'comedian',
 'commercial',
 'company',
 'compare',
 'computer',
 'construction',
 'contractor',
 'contractors',
 'copywriter',
 'costs',
 'counsellor',
 'coverage',
 'craft',
 'dance',
 'data',
 'decorator',
 'decorators',
 'design',
 'designer',
 'domestic',
 'electrical',
 'electricians',
 'employees',
 'engineer',
 'engineering',
 'engineers',
 'entertainer',
 'entertainers',
 'erector',
 'erectors',
 'estate',
 'europe',
 'exporting',
 'fitter',
 'fitters',
 'football',
 'forwarder',
 "forwarder's",
 'furniture',
 'garden',
 'gas',
 'get',
 'glaziers',
 'group',
 'holders',
 'home',
 'how',
 'indemnity',
 'instructor',
 'instructors',
 'insuring',
 'interior',
 'islands',
 'it',
 'joiner',
 'joiners',
 'joinery',
 'land',
 'lawyer',
 'lawyers',
 'legal',
 'limited',
 'london',
 'maker',
 'makers',
 'marin',
 'market',
 'marketing',
 'markets',
 'martial',
 'masonry',
 'mixed',
 'musician',
 'musicians',
 'outside',
 'painter',
 'painters',
 'party',
 'pl',
 'plasterer',
 'plasterers',
 'plumber',
 'plumbers',
 'pound',
 'prices',
 'processor',
 'professional',
 'programmer',
 'providers',
 'publisher',
 'quantity',
 'school',
 'shipments',
 'sign',
 'sports',
 'stall',
 'stallholder',
 'stallholders',
 'stalls',
 'stonemason',
 'student',
 'students',
 'surveyor',
 'surveyors',
 'teacher',
 'teachers',
 'the',
 'therapist',
 'to',
 'trader',
 'tradesman',
 'trading',
 'transport',
 'union',
 'web',
 'website',
 'window',
 'worker']

In [437]:
# Read the file with all your search queries, and save them into a data frame.
my_ads_pool = pd.read_csv('input_data.csv',names = ["keyword_phrases", "clicks", "cost", "transactions", "bounce_rate"])
my_ads_pool

,keyword_phrases,clicks,cost,transactions,bounce_rate
0,actress insurance,5,14.66,0,100%
1,ship cargo insurance,8,30.94,0,83%
2,architect pl insurance,1,4.99,0,100%
3,builder public liability insurance,1,4.31,0,100%
4,channel islands insurance brokers,83,191.80,0,50%
5,compare public liability insurance,3,18.77,0,100%
6,computer programmer insurance,1,1.48,0,100%
7,copywriter insurance,6,23.08,0,67%
8,cost of public liability insurance,3,17.38,0,100%
9,dance instructor insurance,18,64.09,0,84%
10,dance instructor public liability,2,4.82,0,50%
11,dance teacher insurance,3,7.04,0,100%
12,electrical public liability insurance,1,3.55,0,100%
13,freight forwarders insurance liability,2,9.47,0,100%
14,insurance dance instructors,1,2.35,0,100%
15,insurance gas fitters,3,11.46,0,100%
16,it contractor public liability,2,9.26,0,100%
17,liability insurance barrister,2,7.55,0,100%
18,liability insurance data processor,3,18.83,0,100%
19,liability insurance electricians,8,42.54,0,100%
20,liability insurance publisher,1,2.24,0,100%
21,marine insurance cover,3,28.53,1,50%
22,marine transit insurance,25,115.12,6,75%
23,masonry insurance,8,16.86,0,75%
24,musicians union public liability insurance,1,8.17,0,100%
25,online public liability insurance,1,10.11,0,100%
26,painters public insurance,1,1.22,0,100%
27,plasterer insurance,1,4.12,0,100%
28,plasterer public liability insurance,1,4.48,0,100%
29,plasterers public liability,4,15.95,0,100%
...,...,...,...,...,...
407,quote public liability insurance,1,4.97,0,0%
408,business marine insurance,1,17.67,0,0%
409,buy public liability insurance online,1,2.65,0,0%
410,cargo insurance,459,1547.48,44,48%
411,carpet cleaner insurance,3,17.19,0,0%
412,vehicle shipping insurance,15,56.68,4,24%
413,cleaner public liability insurance,1,4.87,0,0%
414,cleaning public liability insurance,1,3.11,0,0%
415,domestic cleaners insurance,1,6.87,0,0%
416,engineering insurance,1,4.00,0,0%
417,engineers liability insurance,1,3.12,0,0%
418,cargo cover,79,201.61,1,84%
419,insurance for copywriter,0,0.00,0,0%
420,insurance painters,1,4.72,0,0%
421,joiner public liability insurance,1,5.93,0,0%
422,liability insurance cover,1,8.48,0,0%
423,marin insurance,1,2.76,0,0%
424,air cargo insurance,6,14.22,2,80%
425,martial arts insurance group,1,2.44,0,0%
426,plumber public liability insurance,2,13.34,0,0%
427,public & employers liability insurance,1,5.36,0,0%
428,public liability for sole trader,2,8.02,0,0%
429,public liability insurance cheap,1,6.48,0,0%
430,public liability insurance for removal companies,1,5.39,0,0%
431,public liability insurance for sign erectors,1,7.19,0,0%
432,public liability insurance for sole traders,2,23.51,0,0%
433,public liability insurance limited company,1,11.82,0,0%
434,self employed domestic cleaner insurance,2,9.18,0,0%
435,self employed public liability,7,59.24,0,0%
436,surveyor liability insurance,1,8.44,0,0%

In [438]:
# Bounce_rate is loaded as an object, and needs to be converted.
my_ads_pool.dtypes

keyword_phrases     object
clicks               int64
cost               float64
transactions         int64
bounce_rate         object
dtype: object

In [439]:
# We need to remove the % sign to be able to work with bounce rate values.
my_ads_pool['bounce_rate'] = pd.to_numeric(my_ads_pool['bounce_rate'].astype(str).str.strip('%'), errors='coerce')

In [440]:
my_ads_pool

,keyword_phrases,clicks,cost,transactions,bounce_rate
0,actress insurance,5,14.66,0,100
1,ship cargo insurance,8,30.94,0,83
2,architect pl insurance,1,4.99,0,100
3,builder public liability insurance,1,4.31,0,100
4,channel islands insurance brokers,83,191.80,0,50
5,compare public liability insurance,3,18.77,0,100
6,computer programmer insurance,1,1.48,0,100
7,copywriter insurance,6,23.08,0,67
8,cost of public liability insurance,3,17.38,0,100
9,dance instructor insurance,18,64.09,0,84
10,dance instructor public liability,2,4.82,0,50
11,dance teacher insurance,3,7.04,0,100
12,electrical public liability insurance,1,3.55,0,100
13,freight forwarders insurance liability,2,9.47,0,100
14,insurance dance instructors,1,2.35,0,100
15,insurance gas fitters,3,11.46,0,100
16,it contractor public liability,2,9.26,0,100
17,liability insurance barrister,2,7.55,0,100
18,liability insurance data processor,3,18.83,0,100
19,liability insurance electricians,8,42.54,0,100
20,liability insurance publisher,1,2.24,0,100
21,marine insurance cover,3,28.53,1,50
22,marine transit insurance,25,115.12,6,75
23,masonry insurance,8,16.86,0,75
24,musicians union public liability insurance,1,8.17,0,100
25,online public liability insurance,1,10.11,0,100
26,painters public insurance,1,1.22,0,100
27,plasterer insurance,1,4.12,0,100
28,plasterer public liability insurance,1,4.48,0,100
29,plasterers public liability,4,15.95,0,100
...,...,...,...,...,...
407,quote public liability insurance,1,4.97,0,0
408,business marine insurance,1,17.67,0,0
409,buy public liability insurance online,1,2.65,0,0
410,cargo insurance,459,1547.48,44,48
411,carpet cleaner insurance,3,17.19,0,0
412,vehicle shipping insurance,15,56.68,4,24
413,cleaner public liability insurance,1,4.87,0,0
414,cleaning public liability insurance,1,3.11,0,0
415,domestic cleaners insurance,1,6.87,0,0
416,engineering insurance,1,4.00,0,0
417,engineers liability insurance,1,3.12,0,0
418,cargo cover,79,201.61,1,84
419,insurance for copywriter,0,0.00,0,0
420,insurance painters,1,4.72,0,0
421,joiner public liability insurance,1,5.93,0,0
422,liability insurance cover,1,8.48,0,0
423,marin insurance,1,2.76,0,0
424,air cargo insurance,6,14.22,2,80
425,martial arts insurance group,1,2.44,0,0
426,plumber public liability insurance,2,13.34,0,0
427,public & employers liability insurance,1,5.36,0,0
428,public liability for sole trader,2,8.02,0,0
429,public liability insurance cheap,1,6.48,0,0
430,public liability insurance for removal companies,1,5.39,0,0
431,public liability insurance for sign erectors,1,7.19,0,0
432,public liability insurance for sole traders,2,23.51,0,0
433,public liability insurance limited company,1,11.82,0,0
434,self employed domestic cleaner insurance,2,9.18,0,0
435,self employed public liability,7,59.24,0,0
436,surveyor liability insurance,1,8.44,0,0

In [441]:
# Bounce rate values are integers now.
my_ads_pool.dtypes

keyword_phrases     object
clicks               int64
cost               float64
transactions         int64
bounce_rate          int64
dtype: object

In [442]:
# The function below is what makes the whole thing work.
# It splits your search queries into words, and checks if any of the words from the list with no convs can be found there.
# If found, they are returned.

In [443]:
#def containsAnyOfTheKeywords(searchTerm):
#    for word in lookup_words_no_convs_words:
#        if searchTerm.startswith(word):
#            return word
#    return ""

def getKeywordsFrom(keywords):
    result = ""
    for keyword in keywords.split():
        for lookup_keyword in lookup_words_no_convs_words:
            if keyword == lookup_keyword:
                result = result + " " + keyword
    return result

print(getKeywordsFrom('insurance for computer programmer'))

 computer programmer

In [444]:
# Next apply the function above on the your data frame with search queries.
# Add a "bad_to_ok_keywords" column, and if the words with no transactions are found, they will be returned here.

In [445]:
my_ads_pool['bad_to_ok_keywords'] = my_ads_pool['keyword_phrases'].apply(
    lambda keywords: getKeywordsFrom(keywords)
)
fitered_df = my_ads_pool.sort_values(by='bad_to_ok_keywords')
fitered_df

,keyword_phrases,clicks,cost,transactions,bounce_rate,bad_to_ok_keywords
410,cargo insurance,459,1547.48,44,48,
106,public liability insurance brokers,2,10.84,0,100,
256,marine insurance,1544,9967.61,108,57,
258,insurance cargo,13,38.52,2,37,
261,insurance for sole traders,24,157.23,2,57,
100,online public liability insurance quote,1,5.66,0,100,
265,sea freight insurance,55,339.56,12,42,
266,liability insurance,17,94.36,0,55,
270,self employed public liability insurance,13,98.39,0,54,
271,freight insurance,294,1051.09,36,48,
429,public liability insurance cheap,1,6.48,0,0,
94,marine liability insurance,35,190.62,2,84,
93,marine liability,2,13.54,0,100,
92,marine insurance brokers uk,1,7.30,0,100,
91,marine cover,1,1.22,0,100,
90,marine cargo insurance quote,2,25.27,1,0,
273,freight cargo insurance,1,2.61,0,0,
274,shipment insurance,105,269.22,15,48,
72,insurance for international shipping,2,8.24,0,100,
149,marine insurance brokers,38,204.95,4,60,
75,insurance for shipping personal effects,1,2.32,0,100,
303,container shipping insurance,15,40.04,5,14,
299,cheap public liability,4,28.38,0,50,
430,public liability insurance for removal companies,1,5.39,0,0,
107,public liability insurance cost,1,3.58,0,100,
294,shipment liability,3,10.02,0,25,
280,cargo liability insurance,18,45.14,0,72,
279,insurance for shipping,6,33.87,1,50,
278,marine insurance car shipping,5,14.86,1,50,
277,public liability insurance 10 million,71,339.22,2,50,
...,...,...,...,...,...,...
127,public liability insurance for stallholders,9,38.34,0,89,stallholders
89,liability insurance for stallholders,10,52.64,0,100,stallholders
163,stallholders insurance,50,154.88,0,78,stallholders
77,insurance for stonemason,1,0.19,0,100,stonemason
436,surveyor liability insurance,1,8.44,0,0,surveyor
348,surveyor insurance,5,27.12,0,33,surveyor
139,surveyor cover,9,35.54,0,83,surveyor
78,insurance for surveyor,3,10.08,0,100,surveyor
202,surveyors liability,16,79.86,0,70,surveyors
228,therapist liability insurance,26,157.78,0,66,therapist
125,insurance therapist,38,83.81,0,89,therapist
135,therapist insurance,113,288.88,0,79,therapist
79,insurance for therapist,4,11.19,0,100,therapist
233,insurance to export a vehicle outside of the uk,15,24.74,0,64,to a outside the
245,car insurance export to europe,7,18.78,0,60,to europe
254,sole trader insurance,6,37.89,0,60,trader
255,sole trader liability,6,23.62,0,60,trader
405,public liability insurance sole trader,1,7.85,0,0,trader
293,public liability sole trader,4,24.85,0,50,trader
335,public liability insurance for sole trader,6,65.04,0,40,trader
428,public liability for sole trader,2,8.02,0,0,trader
218,sole trader public liability insurance,27,242.16,0,46,trader
38,tradesman public liability insurance,5,32.16,0,100,tradesman
95,marine transport insurance,2,8.70,0,100,transport
398,insurance web marketing,1,3.40,0,0,web marketing
40,website designer liability insurance,1,3.46,0,100,website designer
39,website designer insurance,1,2.48,0,100,website designer
363,insurance for window cleaners,4,12.85,0,25,window cleaners
150,public liability window cleaners,7,24.05,0,80,window cleaners
226,window cleaning public liability insurance,4,20.41,0,67,window cleaning

In [446]:
# Remove empty rows.
final_no_convs = fitered_df[fitered_df.bad_to_ok_keywords.str.contains(' ')]
final_no_convs

,keyword_phrases,clicks,cost,transactions,bounce_rate,bad_to_ok_keywords
427,public & employers liability insurance,1,5.36,0,0,&
244,10m public liability insurance,5,38.54,0,60,10m
296,5m public liability insurance,7,60.42,0,50,5m
260,public liability insurance 5m,16,124.96,0,57,5m
306,insurance for shipping a car overseas,4,6.75,0,50,a
252,public liability insurance for a craft stall,5,27.39,0,60,a craft stall
263,actor public liability,21,82.62,0,55,actor
147,insurance for actors,27,44.28,0,81,actors
0,actress insurance,5,14.66,0,100,actress
148,architect liability insurance,7,51.49,0,80,architect
42,architect insurance,1,6.56,0,100,architect
141,insurance for architect,12,117.15,0,83,architect
2,architect pl insurance,1,4.99,0,100,architect pl
219,author liability insurance,20,63.32,0,63,author
158,band public liability insurance,34,145.37,0,73,band
166,band liability insurance,14,63.60,0,77,band
86,liability insurance for bands,5,24.94,0,100,bands
334,public liability insurance for bands uk,6,22.26,0,40,bands
210,bands liability insurance,3,17.63,0,67,bands
123,bands insurance,50,154.41,0,96,bands
144,public liability insurance for bands,6,27.00,0,83,bands
176,public liability insurance bands uk,3,9.63,0,75,bands
105,public liability insurance bands,6,26.24,0,100,bands
178,barber insurance uk,10,28.76,0,75,barber
67,insurance for barrister,4,6.29,0,100,barrister
17,liability insurance barrister,2,7.55,0,100,barrister
129,barrister insurance,9,23.48,0,88,barrister
304,insurance broker marine,2,8.07,0,50,broker
389,cargo insurance broker,2,6.96,0,100,broker
332,marine insurance broker,11,48.88,0,40,broker
...,...,...,...,...,...,...
127,public liability insurance for stallholders,9,38.34,0,89,stallholders
89,liability insurance for stallholders,10,52.64,0,100,stallholders
163,stallholders insurance,50,154.88,0,78,stallholders
77,insurance for stonemason,1,0.19,0,100,stonemason
436,surveyor liability insurance,1,8.44,0,0,surveyor
348,surveyor insurance,5,27.12,0,33,surveyor
139,surveyor cover,9,35.54,0,83,surveyor
78,insurance for surveyor,3,10.08,0,100,surveyor
202,surveyors liability,16,79.86,0,70,surveyors
228,therapist liability insurance,26,157.78,0,66,therapist
125,insurance therapist,38,83.81,0,89,therapist
135,therapist insurance,113,288.88,0,79,therapist
79,insurance for therapist,4,11.19,0,100,therapist
233,insurance to export a vehicle outside of the uk,15,24.74,0,64,to a outside the
245,car insurance export to europe,7,18.78,0,60,to europe
254,sole trader insurance,6,37.89,0,60,trader
255,sole trader liability,6,23.62,0,60,trader
405,public liability insurance sole trader,1,7.85,0,0,trader
293,public liability sole trader,4,24.85,0,50,trader
335,public liability insurance for sole trader,6,65.04,0,40,trader
428,public liability for sole trader,2,8.02,0,0,trader
218,sole trader public liability insurance,27,242.16,0,46,trader
38,tradesman public liability insurance,5,32.16,0,100,tradesman
95,marine transport insurance,2,8.70,0,100,transport
398,insurance web marketing,1,3.40,0,0,web marketing
40,website designer liability insurance,1,3.46,0,100,website designer
39,website designer insurance,1,2.48,0,100,website designer
363,insurance for window cleaners,4,12.85,0,25,window cleaners
150,public liability window cleaners,7,24.05,0,80,window cleaners
226,window cleaning public liability insurance,4,20.41,0,67,window cleaning

In [447]:
# Get bounce rate averages for duplicate words and phrases.
# This will help us later to split them into bad and ok keywords.
final_df_avg = final_no_convs.groupby("bad_to_ok_keywords").mean().drop(['clicks', 'cost', 'transactions'], axis=1)
final_df_avg.reset_index(inplace=True)
final_df_avg_sorted = final_df_avg.sort_values(by='bad_to_ok_keywords', ascending=True)
final_df_avg_sorted

                        bad_to_ok_keywords  bounce_rate
0                                        &     0.000000
1                                      10m    60.000000
2                                       5m    53.500000
3                                        a    50.000000
4                            a craft stall    60.000000
5                                    actor    55.000000
6                                   actors    81.000000
7                                  actress   100.000000
8                                architect    87.666667
9                             architect pl   100.000000
10                                  author    63.000000
11                                    band    75.000000
12                                   bands    80.142857
13                                  barber    75.000000
14                               barrister    96.000000
15                                  broker    58.000000
16                                 builder   100.000000
17                                builders    73.333333
18                       building surveyor     0.000000
19                                business     0.000000
20                                     buy     0.000000
21                          cake decorator    63.000000
22                              cake maker    63.500000
23                             cake makers    50.000000
24                               carpenter   100.000000
25                              carpenters   100.000000
26                          carpet cleaner     0.000000
27                         channel islands    33.333333
28                                cheapest    75.000000
29            children's party entertainer    61.000000
..                                     ...          ...
122                               painters    62.888889
123                              plasterer   100.000000
124                             plasterers    83.333333
125                                plumber    43.000000
126                               plumbers    80.714286
127                                  pound    54.000000
128                                 prices   100.000000
129   professional indemnity it contractor   100.000000
130                              providers   100.000000
131                              publisher    65.750000
132                      quantity surveyor   100.000000
133                           sign erector   100.000000
134                          sign erectors    50.000000
135                                 sports    72.000000
136                          stall holders    83.000000
137                            stallholder    73.000000
138                           stallholders    89.000000
139                             stonemason   100.000000
140                               surveyor    54.000000
141                              surveyors    70.000000
142                              therapist    83.500000
143                       to a outside the    64.000000
144                              to europe    60.000000
145                                 trader    36.571429
146                              tradesman   100.000000
147                              transport   100.000000
148                          web marketing     0.000000
149                       website designer   100.000000
150                        window cleaners    52.500000
151                        window cleaning    67.000000

[152 rows x 2 columns]

In [448]:
# Sum up clicks and cost, and add them in the column next to bad_to_ok_keywords.
final_df_sum = final_no_convs.groupby("bad_to_ok_keywords").sum().drop(['bounce_rate'], axis = 1)
final_df_sum.reset_index(inplace=True)
final_df_sum_sorted = final_df_sum.sort_values(by='bad_to_ok_keywords', ascending=True)
final_df_sum_sorted

                        bad_to_ok_keywords  clicks    cost  transactions
0                                        &       1    5.36             0
1                                      10m       5   38.54             0
2                                       5m      23  185.38             0
3                                        a       4    6.75             0
4                            a craft stall       5   27.39             0
5                                    actor      21   82.62             0
6                                   actors      27   44.28             0
7                                  actress       5   14.66             0
8                                architect      20  175.20             0
9                             architect pl       1    4.99             0
10                                  author      20   63.32             0
11                                    band      48  208.97             0
12                                   bands      79  282.11             0
13                                  barber      10   28.76             0
14                               barrister      15   37.32             0
15                                  broker      20   89.21             0
16                                 builder       1    4.31             0
17                                builders      15   93.69             0
18                       building surveyor       1    5.05             0
19                                business       1   17.67             0
20                                     buy       1    2.65             0
21                          cake decorator      11   53.45             0
22                              cake maker      24  129.34             0
23                             cake makers       8   58.39             0
24                               carpenter       1    3.04             0
25                              carpenters       1    7.74             0
26                          carpet cleaner       3   17.19             0
27                         channel islands     258  590.01             0
28                                cheapest     123  861.40             0
29            children's party entertainer      17   29.37             0
..                                     ...     ...     ...           ...
122                               painters      32  153.03             0
123                              plasterer       2    8.60             0
124                             plasterers       9   38.21             0
125                                plumber       9   59.21             0
126                               plumbers      35  175.64             0
127                                  pound      13   93.84             0
128                                 prices       2    8.53             0
129   professional indemnity it contractor       2   16.44             0
130                              providers       2    9.18             0
131                              publisher      36   85.08             0
132                      quantity surveyor       2    7.99             0
133                           sign erector       1    0.49             0
134                          sign erectors       2    7.82             0
135                                 sports      29   97.70             0
136                          stall holders      43  181.85             0
137                            stallholder      11   27.63             0
138                           stallholders      69  245.86             0
139                             stonemason       1    0.19             0
140                               surveyor      18   81.18             0
141                              surveyors      16   79.86             0
142                              therapist     181  541.66             0
143                       to a outside the      15   24.74             0
144                              to europe       7   18.78             0
145                                 trader      52  409.43             0
146                              tradesman       5   32.16             0
147                              transport       2    8.70             0
148                          web marketing       1    3.40             0
149                       website designer       2    5.94             0
150                        window cleaners      11   36.90             0
151                        window cleaning       4   20.41             0

[152 rows x 4 columns]

In [449]:
# Concatenate final_df_avg_sorted and final_df_sum_sorted.
final_sums_and_avgs = pd.merge(final_df_sum_sorted, final_df_avg_sorted, on='bad_to_ok_keywords')
final_sums_and_avgs

,bad_to_ok_keywords,clicks,cost,transactions,bounce_rate
0,&,1,5.36,0,0.000000
1,10m,5,38.54,0,60.000000
2,5m,23,185.38,0,53.500000
3,a,4,6.75,0,50.000000
4,a craft stall,5,27.39,0,60.000000
5,actor,21,82.62,0,55.000000
6,actors,27,44.28,0,81.000000
7,actress,5,14.66,0,100.000000
8,architect,20,175.20,0,87.666667
9,architect pl,1,4.99,0,100.000000
10,author,20,63.32,0,63.000000
11,band,48,208.97,0,75.000000
12,bands,79,282.11,0,80.142857
13,barber,10,28.76,0,75.000000
14,barrister,15,37.32,0,96.000000
15,broker,20,89.21,0,58.000000
16,builder,1,4.31,0,100.000000
17,builders,15,93.69,0,73.333333
18,building surveyor,1,5.05,0,0.000000
19,business,1,17.67,0,0.000000
20,buy,1,2.65,0,0.000000
21,cake decorator,11,53.45,0,63.000000
22,cake maker,24,129.34,0,63.500000
23,cake makers,8,58.39,0,50.000000
24,carpenter,1,3.04,0,100.000000
25,carpenters,1,7.74,0,100.000000
26,carpet cleaner,3,17.19,0,0.000000
27,channel islands,258,590.01,0,33.333333
28,cheapest,123,861.40,0,75.000000
29,children's party entertainer,17,29.37,0,61.000000
...,...,...,...,...,...
122,painters,32,153.03,0,62.888889
123,plasterer,2,8.60,0,100.000000
124,plasterers,9,38.21,0,83.333333
125,plumber,9,59.21,0,43.000000
126,plumbers,35,175.64,0,80.714286
127,pound,13,93.84,0,54.000000
128,prices,2,8.53,0,100.000000
129,professional indemnity it contractor,2,16.44,0,100.000000
130,providers,2,9.18,0,100.000000
131,publisher,36,85.08,0,65.750000
132,quantity surveyor,2,7.99,0,100.000000
133,sign erector,1,0.49,0,100.000000
134,sign erectors,2,7.82,0,50.000000
135,sports,29,97.70,0,72.000000
136,stall holders,43,181.85,0,83.000000
137,stallholder,11,27.63,0,73.000000
138,stallholders,69,245.86,0,89.000000
139,stonemason,1,0.19,0,100.000000
140,surveyor,18,81.18,0,54.000000
141,surveyors,16,79.86,0,70.000000
142,therapist,181,541.66,0,83.500000
143,to a outside the,15,24.74,0,64.000000
144,to europe,7,18.78,0,60.000000
145,trader,52,409.43,0,36.571429
146,tradesman,5,32.16,0,100.000000
147,transport,2,8.70,0,100.000000
148,web marketing,1,3.40,0,0.000000
149,website designer,2,5.94,0,100.000000
150,window cleaners,11,36.90,0,52.500000
151,window cleaning,4,20.41,0,67.000000

In [450]:
# Rename the columns to indicate sums and avgs.
final_sums_and_avgs.columns = ['bad_to_ok_keywords', 'clicks_sum',  'cost_sum', 'transactions_sum', 'bounce_rate_avg']
final_sums_and_avgs

,bad_to_ok_keywords,clicks_sum,cost_sum,transactions_sum,bounce_rate_avg
0,&,1,5.36,0,0.000000
1,10m,5,38.54,0,60.000000
2,5m,23,185.38,0,53.500000
3,a,4,6.75,0,50.000000
4,a craft stall,5,27.39,0,60.000000
5,actor,21,82.62,0,55.000000
6,actors,27,44.28,0,81.000000
7,actress,5,14.66,0,100.000000
8,architect,20,175.20,0,87.666667
9,architect pl,1,4.99,0,100.000000
10,author,20,63.32,0,63.000000
11,band,48,208.97,0,75.000000
12,bands,79,282.11,0,80.142857
13,barber,10,28.76,0,75.000000
14,barrister,15,37.32,0,96.000000
15,broker,20,89.21,0,58.000000
16,builder,1,4.31,0,100.000000
17,builders,15,93.69,0,73.333333
18,building surveyor,1,5.05,0,0.000000
19,business,1,17.67,0,0.000000
20,buy,1,2.65,0,0.000000
21,cake decorator,11,53.45,0,63.000000
22,cake maker,24,129.34,0,63.500000
23,cake makers,8,58.39,0,50.000000
24,carpenter,1,3.04,0,100.000000
25,carpenters,1,7.74,0,100.000000
26,carpet cleaner,3,17.19,0,0.000000
27,channel islands,258,590.01,0,33.333333
28,cheapest,123,861.40,0,75.000000
29,children's party entertainer,17,29.37,0,61.000000
...,...,...,...,...,...
122,painters,32,153.03,0,62.888889
123,plasterer,2,8.60,0,100.000000
124,plasterers,9,38.21,0,83.333333
125,plumber,9,59.21,0,43.000000
126,plumbers,35,175.64,0,80.714286
127,pound,13,93.84,0,54.000000
128,prices,2,8.53,0,100.000000
129,professional indemnity it contractor,2,16.44,0,100.000000
130,providers,2,9.18,0,100.000000
131,publisher,36,85.08,0,65.750000
132,quantity surveyor,2,7.99,0,100.000000
133,sign erector,1,0.49,0,100.000000
134,sign erectors,2,7.82,0,50.000000
135,sports,29,97.70,0,72.000000
136,stall holders,43,181.85,0,83.000000
137,stallholder,11,27.63,0,73.000000
138,stallholders,69,245.86,0,89.000000
139,stonemason,1,0.19,0,100.000000
140,surveyor,18,81.18,0,54.000000
141,surveyors,16,79.86,0,70.000000
142,therapist,181,541.66,0,83.500000
143,to a outside the,15,24.74,0,64.000000
144,to europe,7,18.78,0,60.000000
145,trader,52,409.43,0,36.571429
146,tradesman,5,32.16,0,100.000000
147,transport,2,8.70,0,100.000000
148,web marketing,1,3.40,0,0.000000
149,website designer,2,5.94,0,100.000000
150,window cleaners,11,36.90,0,52.500000
151,window cleaning,4,20.41,0,67.000000

In [451]:
# Categorise words and phrases as "ok" or "bad" based on the following criateries:
# =100% bounce rate - bad
# <100% bounce rate - ok
# Save the result to csv 
final_sums_and_avgs['category'] = np.where(final_sums_and_avgs['bounce_rate_avg']<100, 'ok', 'bad')
final_sums_and_avgs

,bad_to_ok_keywords,clicks_sum,cost_sum,transactions_sum,bounce_rate_avg,category
0,&,1,5.36,0,0.000000,ok
1,10m,5,38.54,0,60.000000,ok
2,5m,23,185.38,0,53.500000,ok
3,a,4,6.75,0,50.000000,ok
4,a craft stall,5,27.39,0,60.000000,ok
5,actor,21,82.62,0,55.000000,ok
6,actors,27,44.28,0,81.000000,ok
7,actress,5,14.66,0,100.000000,bad
8,architect,20,175.20,0,87.666667,ok
9,architect pl,1,4.99,0,100.000000,bad
10,author,20,63.32,0,63.000000,ok
11,band,48,208.97,0,75.000000,ok
12,bands,79,282.11,0,80.142857,ok
13,barber,10,28.76,0,75.000000,ok
14,barrister,15,37.32,0,96.000000,ok
15,broker,20,89.21,0,58.000000,ok
16,builder,1,4.31,0,100.000000,bad
17,builders,15,93.69,0,73.333333,ok
18,building surveyor,1,5.05,0,0.000000,ok
19,business,1,17.67,0,0.000000,ok
20,buy,1,2.65,0,0.000000,ok
21,cake decorator,11,53.45,0,63.000000,ok
22,cake maker,24,129.34,0,63.500000,ok
23,cake makers,8,58.39,0,50.000000,ok
24,carpenter,1,3.04,0,100.000000,bad
25,carpenters,1,7.74,0,100.000000,bad
26,carpet cleaner,3,17.19,0,0.000000,ok
27,channel islands,258,590.01,0,33.333333,ok
28,cheapest,123,861.40,0,75.000000,ok
29,children's party entertainer,17,29.37,0,61.000000,ok
...,...,...,...,...,...,...
122,painters,32,153.03,0,62.888889,ok
123,plasterer,2,8.60,0,100.000000,bad
124,plasterers,9,38.21,0,83.333333,ok
125,plumber,9,59.21,0,43.000000,ok
126,plumbers,35,175.64,0,80.714286,ok
127,pound,13,93.84,0,54.000000,ok
128,prices,2,8.53,0,100.000000,bad
129,professional indemnity it contractor,2,16.44,0,100.000000,bad
130,providers,2,9.18,0,100.000000,bad
131,publisher,36,85.08,0,65.750000,ok
132,quantity surveyor,2,7.99,0,100.000000,bad
133,sign erector,1,0.49,0,100.000000,bad
134,sign erectors,2,7.82,0,50.000000,ok
135,sports,29,97.70,0,72.000000,ok
136,stall holders,43,181.85,0,83.000000,ok
137,stallholder,11,27.63,0,73.000000,ok
138,stallholders,69,245.86,0,89.000000,ok
139,stonemason,1,0.19,0,100.000000,bad
140,surveyor,18,81.18,0,54.000000,ok
141,surveyors,16,79.86,0,70.000000,ok
142,therapist,181,541.66,0,83.500000,ok
143,to a outside the,15,24.74,0,64.000000,ok
144,to europe,7,18.78,0,60.000000,ok
145,trader,52,409.43,0,36.571429,ok
146,tradesman,5,32.16,0,100.000000,bad
147,transport,2,8.70,0,100.000000,bad
148,web marketing,1,3.40,0,0.000000,ok
149,website designer,2,5.94,0,100.000000,bad
150,window cleaners,11,36.90,0,52.500000,ok
151,window cleaning,4,20.41,0,67.000000,ok

In [452]:
# Turn bounce rate to int.
final_sums_and_avgs['bounce_rate_avg'] = pd.to_numeric(final_sums_and_avgs['bounce_rate_avg'].astype(int))
final_sums_and_avgs

,bad_to_ok_keywords,clicks_sum,cost_sum,transactions_sum,bounce_rate_avg,category
0,&,1,5.36,0,0,ok
1,10m,5,38.54,0,60,ok
2,5m,23,185.38,0,53,ok
3,a,4,6.75,0,50,ok
4,a craft stall,5,27.39,0,60,ok
5,actor,21,82.62,0,55,ok
6,actors,27,44.28,0,81,ok
7,actress,5,14.66,0,100,bad
8,architect,20,175.20,0,87,ok
9,architect pl,1,4.99,0,100,bad
10,author,20,63.32,0,63,ok
11,band,48,208.97,0,75,ok
12,bands,79,282.11,0,80,ok
13,barber,10,28.76,0,75,ok
14,barrister,15,37.32,0,96,ok
15,broker,20,89.21,0,58,ok
16,builder,1,4.31,0,100,bad
17,builders,15,93.69,0,73,ok
18,building surveyor,1,5.05,0,0,ok
19,business,1,17.67,0,0,ok
20,buy,1,2.65,0,0,ok
21,cake decorator,11,53.45,0,63,ok
22,cake maker,24,129.34,0,63,ok
23,cake makers,8,58.39,0,50,ok
24,carpenter,1,3.04,0,100,bad
25,carpenters,1,7.74,0,100,bad
26,carpet cleaner,3,17.19,0,0,ok
27,channel islands,258,590.01,0,33,ok
28,cheapest,123,861.40,0,75,ok
29,children's party entertainer,17,29.37,0,61,ok
...,...,...,...,...,...,...
122,painters,32,153.03,0,62,ok
123,plasterer,2,8.60,0,100,bad
124,plasterers,9,38.21,0,83,ok
125,plumber,9,59.21,0,43,ok
126,plumbers,35,175.64,0,80,ok
127,pound,13,93.84,0,54,ok
128,prices,2,8.53,0,100,bad
129,professional indemnity it contractor,2,16.44,0,100,bad
130,providers,2,9.18,0,100,bad
131,publisher,36,85.08,0,65,ok
132,quantity surveyor,2,7.99,0,100,bad
133,sign erector,1,0.49,0,100,bad
134,sign erectors,2,7.82,0,50,ok
135,sports,29,97.70,0,72,ok
136,stall holders,43,181.85,0,83,ok
137,stallholder,11,27.63,0,73,ok
138,stallholders,69,245.86,0,89,ok
139,stonemason,1,0.19,0,100,bad
140,surveyor,18,81.18,0,54,ok
141,surveyors,16,79.86,0,70,ok
142,therapist,181,541.66,0,83,ok
143,to a outside the,15,24.74,0,64,ok
144,to europe,7,18.78,0,60,ok
145,trader,52,409.43,0,36,ok
146,tradesman,5,32.16,0,100,bad
147,transport,2,8.70,0,100,bad
148,web marketing,1,3.40,0,0,ok
149,website designer,2,5.94,0,100,bad
150,window cleaners,11,36.90,0,52,ok
151,window cleaning,4,20.41,0,67,ok

In [453]:
# Save the dataframe with search queries that include words/phrases that did not convert in the new data frame: final_no_convs_pool. 
final_no_convs_pool = final_no_convs.reset_index(drop=True)
final_no_convs_pool

,keyword_phrases,clicks,cost,transactions,bounce_rate,bad_to_ok_keywords
0,public & employers liability insurance,1,5.36,0,0,&
1,10m public liability insurance,5,38.54,0,60,10m
2,5m public liability insurance,7,60.42,0,50,5m
3,public liability insurance 5m,16,124.96,0,57,5m
4,insurance for shipping a car overseas,4,6.75,0,50,a
5,public liability insurance for a craft stall,5,27.39,0,60,a craft stall
6,actor public liability,21,82.62,0,55,actor
7,insurance for actors,27,44.28,0,81,actors
8,actress insurance,5,14.66,0,100,actress
9,architect liability insurance,7,51.49,0,80,architect
10,architect insurance,1,6.56,0,100,architect
11,insurance for architect,12,117.15,0,83,architect
12,architect pl insurance,1,4.99,0,100,architect pl
13,author liability insurance,20,63.32,0,63,author
14,band public liability insurance,34,145.37,0,73,band
15,band liability insurance,14,63.60,0,77,band
16,liability insurance for bands,5,24.94,0,100,bands
17,public liability insurance for bands uk,6,22.26,0,40,bands
18,bands liability insurance,3,17.63,0,67,bands
19,bands insurance,50,154.41,0,96,bands
20,public liability insurance for bands,6,27.00,0,83,bands
21,public liability insurance bands uk,3,9.63,0,75,bands
22,public liability insurance bands,6,26.24,0,100,bands
23,barber insurance uk,10,28.76,0,75,barber
24,insurance for barrister,4,6.29,0,100,barrister
25,liability insurance barrister,2,7.55,0,100,barrister
26,barrister insurance,9,23.48,0,88,barrister
27,insurance broker marine,2,8.07,0,50,broker
28,cargo insurance broker,2,6.96,0,100,broker
29,marine insurance broker,11,48.88,0,40,broker
...,...,...,...,...,...,...
267,public liability insurance for stallholders,9,38.34,0,89,stallholders
268,liability insurance for stallholders,10,52.64,0,100,stallholders
269,stallholders insurance,50,154.88,0,78,stallholders
270,insurance for stonemason,1,0.19,0,100,stonemason
271,surveyor liability insurance,1,8.44,0,0,surveyor
272,surveyor insurance,5,27.12,0,33,surveyor
273,surveyor cover,9,35.54,0,83,surveyor
274,insurance for surveyor,3,10.08,0,100,surveyor
275,surveyors liability,16,79.86,0,70,surveyors
276,therapist liability insurance,26,157.78,0,66,therapist
277,insurance therapist,38,83.81,0,89,therapist
278,therapist insurance,113,288.88,0,79,therapist
279,insurance for therapist,4,11.19,0,100,therapist
280,insurance to export a vehicle outside of the uk,15,24.74,0,64,to a outside the
281,car insurance export to europe,7,18.78,0,60,to europe
282,sole trader insurance,6,37.89,0,60,trader
283,sole trader liability,6,23.62,0,60,trader
284,public liability insurance sole trader,1,7.85,0,0,trader
285,public liability sole trader,4,24.85,0,50,trader
286,public liability insurance for sole trader,6,65.04,0,40,trader
287,public liability for sole trader,2,8.02,0,0,trader
288,sole trader public liability insurance,27,242.16,0,46,trader
289,tradesman public liability insurance,5,32.16,0,100,tradesman
290,marine transport insurance,2,8.70,0,100,transport
291,insurance web marketing,1,3.40,0,0,web marketing
292,website designer liability insurance,1,3.46,0,100,website designer
293,website designer insurance,1,2.48,0,100,website designer
294,insurance for window cleaners,4,12.85,0,25,window cleaners
295,public liability window cleaners,7,24.05,0,80,window cleaners
296,window cleaning public liability insurance,4,20.41,0,67,window cleaning

In [454]:
# Add to the above dataframe to the words/phrases and their sums and avgs next to them.
final_result = pd.merge(final_no_convs_pool, final_sums_and_avgs, on='bad_to_ok_keywords')
final_result_drop_columns = final_result.drop(['transactions_sum','bounce_rate'], axis=1)
final_result_drop_columns

,keyword_phrases,clicks,cost,transactions,bad_to_ok_keywords,clicks_sum,cost_sum,bounce_rate_avg,category
0,public & employers liability insurance,1,5.36,0,&,1,5.36,0,ok
1,10m public liability insurance,5,38.54,0,10m,5,38.54,60,ok
2,5m public liability insurance,7,60.42,0,5m,23,185.38,53,ok
3,public liability insurance 5m,16,124.96,0,5m,23,185.38,53,ok
4,insurance for shipping a car overseas,4,6.75,0,a,4,6.75,50,ok
5,public liability insurance for a craft stall,5,27.39,0,a craft stall,5,27.39,60,ok
6,actor public liability,21,82.62,0,actor,21,82.62,55,ok
7,insurance for actors,27,44.28,0,actors,27,44.28,81,ok
8,actress insurance,5,14.66,0,actress,5,14.66,100,bad
9,architect liability insurance,7,51.49,0,architect,20,175.20,87,ok
10,architect insurance,1,6.56,0,architect,20,175.20,87,ok
11,insurance for architect,12,117.15,0,architect,20,175.20,87,ok
12,architect pl insurance,1,4.99,0,architect pl,1,4.99,100,bad
13,author liability insurance,20,63.32,0,author,20,63.32,63,ok
14,band public liability insurance,34,145.37,0,band,48,208.97,75,ok
15,band liability insurance,14,63.60,0,band,48,208.97,75,ok
16,liability insurance for bands,5,24.94,0,bands,79,282.11,80,ok
17,public liability insurance for bands uk,6,22.26,0,bands,79,282.11,80,ok
18,bands liability insurance,3,17.63,0,bands,79,282.11,80,ok
19,bands insurance,50,154.41,0,bands,79,282.11,80,ok
20,public liability insurance for bands,6,27.00,0,bands,79,282.11,80,ok
21,public liability insurance bands uk,3,9.63,0,bands,79,282.11,80,ok
22,public liability insurance bands,6,26.24,0,bands,79,282.11,80,ok
23,barber insurance uk,10,28.76,0,barber,10,28.76,75,ok
24,insurance for barrister,4,6.29,0,barrister,15,37.32,96,ok
25,liability insurance barrister,2,7.55,0,barrister,15,37.32,96,ok
26,barrister insurance,9,23.48,0,barrister,15,37.32,96,ok
27,insurance broker marine,2,8.07,0,broker,20,89.21,58,ok
28,cargo insurance broker,2,6.96,0,broker,20,89.21,58,ok
29,marine insurance broker,11,48.88,0,broker,20,89.21,58,ok
...,...,...,...,...,...,...,...,...,...
267,public liability insurance for stallholders,9,38.34,0,stallholders,69,245.86,89,ok
268,liability insurance for stallholders,10,52.64,0,stallholders,69,245.86,89,ok
269,stallholders insurance,50,154.88,0,stallholders,69,245.86,89,ok
270,insurance for stonemason,1,0.19,0,stonemason,1,0.19,100,bad
271,surveyor liability insurance,1,8.44,0,surveyor,18,81.18,54,ok
272,surveyor insurance,5,27.12,0,surveyor,18,81.18,54,ok
273,surveyor cover,9,35.54,0,surveyor,18,81.18,54,ok
274,insurance for surveyor,3,10.08,0,surveyor,18,81.18,54,ok
275,surveyors liability,16,79.86,0,surveyors,16,79.86,70,ok
276,therapist liability insurance,26,157.78,0,therapist,181,541.66,83,ok
277,insurance therapist,38,83.81,0,therapist,181,541.66,83,ok
278,therapist insurance,113,288.88,0,therapist,181,541.66,83,ok
279,insurance for therapist,4,11.19,0,therapist,181,541.66,83,ok
280,insurance to export a vehicle outside of the uk,15,24.74,0,to a outside the,15,24.74,64,ok
281,car insurance export to europe,7,18.78,0,to europe,7,18.78,60,ok
282,sole trader insurance,6,37.89,0,trader,52,409.43,36,ok
283,sole trader liability,6,23.62,0,trader,52,409.43,36,ok
284,public liability insurance sole trader,1,7.85,0,trader,52,409.43,36,ok
285,public liability sole trader,4,24.85,0,trader,52,409.43,36,ok
286,public liability insurance for sole trader,6,65.04,0,trader,52,409.43,36,ok
287,public liability for sole trader,2,8.02,0,trader,52,409.43,36,ok
288,sole trader public liability insurance,27,242.16,0,trader,52,409.43,36,ok
289,tradesman public liability insurance,5,32.16,0,tradesman,5,32.16,100,bad
290,marine transport insurance,2,8.70,0,transport,2,8.70,100,bad
291,insurance web marketing,1,3.40,0,web marketing,1,3.40,0,ok
292,website designer liability insurance,1,3.46,0,website designer,2,5.94,100,bad
293,website designer insurance,1,2.48,0,website designer,2,5.94,100,bad
294,insurance for window cleaners,4,12.85,0,window cleaners,11,36.90,52,ok
295,public liability window cleaners,7,24.05,0,window cleaners,11,36.90,52,ok
296,window cleaning public liability insurance,4,20.41,0,window cleaning,4,20.41,67,ok

In [455]:
final_result_drop_columns.to_csv('2-ppc_bad_to_ok.csv', index = False)

In [456]:
# Part III.
# Find out if we can find queries from GA's Search Queries report in the search queries export from Search Console.
# We want to see if we rank for them, or if we even have relevant content that addresses those queries.
# If we do, we can carefully increase the prominence of those keywords by making sure they are present in key areas,
# such as titles, H1 tags, and descriptions, as well as in the anchor text of selected internal links.

In [457]:
# Read the input data file or the data frame with this data.
inputData = pd.read_csv('input_data.csv',names = ["keyword_phrases", "clicks", "cost", "transactions", "bounce_rate"])
inputData

,keyword_phrases,clicks,cost,transactions,bounce_rate
0,actress insurance,5,14.66,0,100%
1,ship cargo insurance,8,30.94,0,83%
2,architect pl insurance,1,4.99,0,100%
3,builder public liability insurance,1,4.31,0,100%
4,channel islands insurance brokers,83,191.80,0,50%
5,compare public liability insurance,3,18.77,0,100%
6,computer programmer insurance,1,1.48,0,100%
7,copywriter insurance,6,23.08,0,67%
8,cost of public liability insurance,3,17.38,0,100%
9,dance instructor insurance,18,64.09,0,84%
10,dance instructor public liability,2,4.82,0,50%
11,dance teacher insurance,3,7.04,0,100%
12,electrical public liability insurance,1,3.55,0,100%
13,freight forwarders insurance liability,2,9.47,0,100%
14,insurance dance instructors,1,2.35,0,100%
15,insurance gas fitters,3,11.46,0,100%
16,it contractor public liability,2,9.26,0,100%
17,liability insurance barrister,2,7.55,0,100%
18,liability insurance data processor,3,18.83,0,100%
19,liability insurance electricians,8,42.54,0,100%
20,liability insurance publisher,1,2.24,0,100%
21,marine insurance cover,3,28.53,1,50%
22,marine transit insurance,25,115.12,6,75%
23,masonry insurance,8,16.86,0,75%
24,musicians union public liability insurance,1,8.17,0,100%
25,online public liability insurance,1,10.11,0,100%
26,painters public insurance,1,1.22,0,100%
27,plasterer insurance,1,4.12,0,100%
28,plasterer public liability insurance,1,4.48,0,100%
29,plasterers public liability,4,15.95,0,100%
...,...,...,...,...,...
407,quote public liability insurance,1,4.97,0,0%
408,business marine insurance,1,17.67,0,0%
409,buy public liability insurance online,1,2.65,0,0%
410,cargo insurance,459,1547.48,44,48%
411,carpet cleaner insurance,3,17.19,0,0%
412,vehicle shipping insurance,15,56.68,4,24%
413,cleaner public liability insurance,1,4.87,0,0%
414,cleaning public liability insurance,1,3.11,0,0%
415,domestic cleaners insurance,1,6.87,0,0%
416,engineering insurance,1,4.00,0,0%
417,engineers liability insurance,1,3.12,0,0%
418,cargo cover,79,201.61,1,84%
419,insurance for copywriter,0,0.00,0,0%
420,insurance painters,1,4.72,0,0%
421,joiner public liability insurance,1,5.93,0,0%
422,liability insurance cover,1,8.48,0,0%
423,marin insurance,1,2.76,0,0%
424,air cargo insurance,6,14.22,2,80%
425,martial arts insurance group,1,2.44,0,0%
426,plumber public liability insurance,2,13.34,0,0%
427,public & employers liability insurance,1,5.36,0,0%
428,public liability for sole trader,2,8.02,0,0%
429,public liability insurance cheap,1,6.48,0,0%
430,public liability insurance for removal companies,1,5.39,0,0%
431,public liability insurance for sign erectors,1,7.19,0,0%
432,public liability insurance for sole traders,2,23.51,0,0%
433,public liability insurance limited company,1,11.82,0,0%
434,self employed domestic cleaner insurance,2,9.18,0,0%
435,self employed public liability,7,59.24,0,0%
436,surveyor liability insurance,1,8.44,0,0%

In [458]:
# Filter out search queries with no conversions.
inputData_with_convs = inputData[(inputData[['transactions']] != 0).all(axis=1)]
inputData_with_convs

,keyword_phrases,clicks,cost,transactions,bounce_rate
21,marine insurance cover,3,28.53,1,50%
22,marine transit insurance,25,115.12,6,75%
31,public and employers liability,3,10.96,1,75%
45,marine insurance for cargo,2,7.42,1,0%
46,marine cargo insurance uk,10,34.79,3,50%
47,marine cargo insurance quote online,2,27.52,1,0%
90,marine cargo insurance quote,2,25.27,1,0%
94,marine liability insurance,35,190.62,2,84%
119,car shipping insurance,50,125.73,7,48%
122,vehicle export insurance,112,259.92,2,83%
128,marine cargo insurance cover,1,13.97,1,0%
138,marine cargo insurance,199,1362.70,26,42%
149,marine insurance brokers,38,204.95,4,60%
169,freight forwarding insurance,25,97.48,2,63%
174,marine insurance shipping,5,21.00,1,38%
200,5 million public liability insurance,29,182.66,1,70%
203,freight forwarders insurance,53,264.77,6,63%
207,export insurance uk car,183,329.94,1,68%
209,marine insurance policy,12,48.48,1,50%
217,shipping container insurance,38,106.86,7,37%
229,shipment cover,16,56.57,2,65%
230,2 million public liability insurance,35,182.56,1,65%
232,car export insurance,873,1936.76,14,64%
241,air freight insurance,61,177.50,5,49%
242,employers liability insurance,5,21.97,1,60%
256,marine insurance,1544,9967.61,108,57%
258,insurance cargo,13,38.52,2,37%
261,insurance for sole traders,24,157.23,2,57%
265,sea freight insurance,55,339.56,12,42%
271,freight insurance,294,1051.09,36,48%
...,...,...,...,...,...
358,marine insurance quote online,4,12.01,2,25%
359,marine shipping insurance,17,63.74,3,19%
360,shipping insurance,1582,6515.15,222,45%
361,marine insurance for car shipping,8,17.87,1,25%
365,car marine insurance,17,54.54,4,10%
366,overseas removals insurance,14,43.92,3,20%
369,freight insurance quote,20,48.62,6,18%
371,shipping insurance container,4,22.85,1,25%
372,insurance shipping personal effects,7,21.22,3,0%
373,marine insurance quote,12,68.37,5,0%
374,shipping insurance quote,5,12.20,2,20%
375,cost of marine insurance,7,38.51,2,0%
376,shipping container insurance uk,6,16.18,3,0%
377,freight container insurance,2,7.84,1,0%
379,marine insurance shipping household goods,2,9.85,1,0%
380,marine insurance vehicles,1,3.41,1,0%
381,cheap freight insurance,1,2.67,1,0%
382,freight forwarders liability insurance,1,2.13,1,0%
383,insurance for container shipping,1,2.61,1,0%
384,insurance for shipping container,2,7.95,1,0%
385,international shipment insurance,3,7.12,1,0%
386,shipping insurance quotes,1,1.96,1,0%
387,cargo insurance uk,54,165.04,9,50%
390,marine transit insurance quote,2,6.92,1,0%
391,ocean freight insurance,4,15.17,1,0%
392,shipping insurance uk,135,409.19,21,35%
410,cargo insurance,459,1547.48,44,48%
412,vehicle shipping insurance,15,56.68,4,24%
418,cargo cover,79,201.61,1,84%
424,air cargo insurance,6,14.22,2,80%

In [459]:
# Import Search Console data into a data frame.
searchConsole = pd.read_csv('search_console_data.csv',names = ["keyword_phrases", "clicks", "impressions", "ctr", "position"])
searchConsole

,keyword_phrases,clicks,impressions,ctr,position
0,keyword 1,2848,8661,32.88%,2.56
1,keyword 2,1162,3580,32.46%,1.04
2,keyword 3,675,2796,24.14%,1.00
3,keyword 4,602,1866,32.26%,2.24
4,keyword 5,199,835,23.83%,1.92
5,keyword 6,198,672,29.46%,1.01
6,keyword 7,184,1025,17.95%,1.77
7,marine cargo insurance cover,148,601,24.63%,1.00
8,freight insurance,124,2121,5.85%,7.34
9,maritime insurance,110,323,34.06%,1.12
10,electrical public liability insurance,106,810,13.09%,3.29
11,freight forwarders insurance liability,100,369,27.10%,1.02
12,insurance dance instructors,98,302,32.45%,1.00
13,insurance gas fitters,97,286,33.92%,1.00
14,it contractor public liability,96,278,34.53%,1.06
15,liability insurance barrister,92,773,11.90%,3.61
16,liability insurance data processor,89,166,53.61%,1.00
17,liability insurance electricians,88,402,21.89%,2.47
18,liability insurance publisher,87,221,39.37%,1.00
19,marine insurance cover,75,490,15.31%,2.07
20,dance instructor insurance,71,211,33.65%,1.08
21,keyword 8,70,477,14.68%,2.77
22,keyword 9,70,213,32.86%,1.25
23,keyword 10,66,512,12.89%,3.37
24,keyword 11,63,159,39.62%,1.00
25,keyword 12,61,167,36.53%,1.23
26,keyword 13,54,308,17.53%,2.97
27,keyword 14,53,636,8.33%,3.86
28,keyword 15,53,191,27.75%,1.82
29,keyword 16,52,116,44.83%,1.05
30,keyword 17,51,386,13.21%,1.23
31,keyword 18,51,259,19.69%,2.29
32,keyword 19,50,164,30.49%,2.63

In [460]:
# Merge with inputData_with_convs frame.
# Return search queries that can be found in both: in Search Console and in GA's Search Queries report.
vlookup = pd.merge(inputData_with_convs, searchConsole, on='keyword_phrases')
vlookup
# You have now a table with search queries and their metrics from GA and SC
# that did convert in the past but also presented in organic search.
# Optimise these queries first.

,keyword_phrases,clicks_x,cost,transactions,bounce_rate,clicks_y,impressions,ctr,position
0,marine insurance cover,3,28.53,1,50%,75,490,15.31%,2.07
1,marine cargo insurance cover,1,13.97,1,0%,148,601,24.63%,1.00
2,freight insurance,294,1051.09,36,48%,124,2121,5.85%,7.34
3,maritime insurance,34,102.48,3,48%,110,323,34.06%,1.12

In [461]:
# We now want to find search queries that did convert BUT cannot be found in Search Console.
# These are the queries that we will want to include into our content.

In [462]:
# Remove clicks_y, impressions, ctr, position columns from vlookup data frame.
vlookup_new = vlookup.drop(['clicks_y','impressions','ctr','position'], axis=1)
vlookup_new.columns = ['keyword_phrases','clicks', 'cost','transactions','bounce_rate']
vlookup_new

                keyword_phrases  clicks     cost  transactions bounce_rate
0        marine insurance cover       3    28.53             1         50%
1  marine cargo insurance cover       1    13.97             1          0%
2             freight insurance     294  1051.09            36         48%
3            maritime insurance      34   102.48             3         48%

In [463]:
vlookup_new.to_csv('3-converted_found_in_search_console.csv', index = False)

In [464]:
# Append one data frame to another.
# Remove duplicate rows.
joined_frames = vlookup_new.append(inputData_with_convs).sort_values(by='keyword_phrases', ascending=False)
not_found_in_search_console_but_converted = joined_frames.drop_duplicates(keep=False)
not_found_in_search_console_but_converted
# Below are search queries that did convert but we do not have any visiability for them at the moment 
# as these were not found in search console.

,keyword_phrases,clicks,cost,transactions,bounce_rate
412,vehicle shipping insurance,15,56.68,4,24%
122,vehicle export insurance,112,259.92,2,83%
275,uk freight insurance,9,29.87,3,50%
392,shipping insurance uk,135,409.19,21,35%
386,shipping insurance quotes,1,1.96,1,0%
374,shipping insurance quote,5,12.20,2,20%
371,shipping insurance container,4,22.85,1,25%
360,shipping insurance,1582,6515.15,222,45%
376,shipping container insurance uk,6,16.18,3,0%
217,shipping container insurance,38,106.86,7,37%
274,shipment insurance,105,269.22,15,48%
229,shipment cover,16,56.57,2,65%
265,sea freight insurance,55,339.56,12,42%
329,public liability self employed,33,240.96,1,42%
277,public liability insurance 10 million,71,339.22,2,50%
31,public and employers liability,3,10.96,1,75%
366,overseas removals insurance,14,43.92,3,20%
391,ocean freight insurance,4,15.17,1,0%
390,marine transit insurance quote,2,6.92,1,0%
350,marine transit insurance for household goods,10,60.60,3,30%
22,marine transit insurance,25,115.12,6,75%
359,marine shipping insurance,17,63.74,3,19%
94,marine liability insurance,35,190.62,2,84%
380,marine insurance vehicles,1,3.41,1,0%
344,marine insurance uk,14,85.13,2,33%
379,marine insurance shipping household goods,2,9.85,1,0%
174,marine insurance shipping,5,21.00,1,38%
358,marine insurance quote online,4,12.01,2,25%
373,marine insurance quote,12,68.37,5,0%
209,marine insurance policy,12,48.48,1,50%
...,...,...,...,...,...
372,insurance shipping personal effects,7,21.22,3,0%
261,insurance for sole traders,24,157.23,2,57%
356,insurance for shipping goods overseas,33,125.46,9,27%
330,insurance for shipping goods,16,49.42,3,41%
384,insurance for shipping container,2,7.95,1,0%
279,insurance for shipping,6,33.87,1,50%
383,insurance for container shipping,1,2.61,1,0%
258,insurance cargo,13,38.52,2,37%
327,household goods shipping insurance,4,9.71,2,0%
369,freight insurance quote,20,48.62,6,18%
169,freight forwarding insurance,25,97.48,2,63%
382,freight forwarders liability insurance,1,2.13,1,0%
203,freight forwarders insurance,53,264.77,6,63%
377,freight container insurance,2,7.84,1,0%
207,export insurance uk car,183,329.94,1,68%
242,employers liability insurance,5,21.97,1,60%
375,cost of marine insurance,7,38.51,2,0%
303,container shipping insurance,15,40.04,5,14%
381,cheap freight insurance,1,2.67,1,0%
276,cargo ship insurance,4,20.20,1,70%
387,cargo insurance uk,54,165.04,9,50%
410,cargo insurance,459,1547.48,44,48%
418,cargo cover,79,201.61,1,84%
119,car shipping insurance,50,125.73,7,48%
365,car marine insurance,17,54.54,4,10%
232,car export insurance,873,1936.76,14,64%
241,air freight insurance,61,177.50,5,49%
424,air cargo insurance,6,14.22,2,80%
200,5 million public liability insurance,29,182.66,1,70%
230,2 million public liability insurance,35,182.56,1,65%

In [465]:
not_found_in_search_console_but_converted.to_csv('4-converted_not_found_in_search_console.csv', index = False)